<script>
	$(document).ready(function()
	{
		$.ajax({
			type: "GET",
			url: 'http://gemsontime.dev/events/1/2012-01-01/2012-12-31',
			async : true,
			dataType: "json",
			success: function(data){	
				for (var key in data) {
					e = new Event();
					e.id = data[key]['id'];
					e.name = data[key]['name'];
					e.isMine = data[key]['isMine'];
					e.date = data[key]['date'];
					
					$('#wrapper').append(e.render());
				}
			}
			});
});
</script>