<?=$this->doctype(); ?>

<html>
	<head>
		<?=$this->headMeta(); ?>

		<title>Gems On Time</title>
		<?=$this->headLink(); ?>

		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<?=$this->headScript(); ?>

	</head>
	<body>
        <header>
            <center><h1>Gems On Time</h1></center>
            <!-- <button id="import_events">IMPORT</button> -->
        </header>
        <?= $this->layout()->content;?>
        <footer>
        	<center><div id="marker"></div></center>
        	<div id="ideas">
			</div>
            <!-- <center><b>Gems on Time</b></center> -->
        </footer>
        <script src="<?=$this->serverUrl()?>/assets/js/lib/jquery.overscroll.min.js"></script>
	</body>
</html>